---
- name: Directory is present
  file:
    path=/data/mongodb
    state=directory
  tags: [mongodb]

- name: Add repository
  yum_repository:
    name: mongodb-org-3.2
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.2/x86_64/
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-3.2.asc

- name: Install package
  yum: name=mongodb-org state=present
