---

- name: install postgresql dependencies
  yum: name={{ item }} state=installed
  with_items:
    - python-psycopg2

- name: install psycopg2 python module
  pip: name=psycopg2

- name: run postgresql
  service:
    name: postgresql-9.6
    state: started

- name: Create database user
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    name: consult
    password: consult
    role_attr_flags: login


- name: create db
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  # Create a new database with name "consult"
  postgresql_db:  name=consult
                  owner=consult
                  encoding='UTF-8'

