---
- name: include vars
  include_vars: "init-config.yml"

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home={{tomcat_name}} createhome=no
  become: True
  become_method: sudo

- name: Create dist download_folder
  command: "mkdir -p {{tomcat_download_folder}} creates={{tomcat_download_folder}}"

- name: Create tomcat folder
  command: "mkdir -p {{tomcat_name}} creates={{tomcat_name}}"

- name: Download tomcat
  get_url:
    url: "{{ tomcat_download_url }}"
    dest: "{{ tomcat_archive }}"

- name: Unpack archive
  command: "tar -zxf {{tomcat_archive}} -C {{tomcat_download_folder}} creates={{tomcat_unpacked}}" 

- name: move Unpacked
  command: "mv -T {{ tomcat_unpacked }} {{tomcat_name}} creates={{tomcat_name}}"
  

- name: Install service
  template: src=tomcat.service.j2 dest=/etc/systemd/system/tomcat.service
  notify: restart tomcat

- name: Enable service
  command: systemctl daemon-reload
  become: True
  become_method: sudo

- name: Configure Tomcat server
  template: 
    src: setenv.sh.j2 
    dest: "{{tomcat_name}}/conf/setenv.sh"
    owner: tomcat
    group: tomcat
    mode: 0740
  notify: restart tomcat

- name: Fix ownership
  file: state=directory path={{tomcat_name}} owner=tomcat group=tomcat recurse=yes
  notify: restart tomcat

- name: wait for tomcat to start
  wait_for: port={{http_port}}