---
- name: Install desired packages
  yum: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - epel-release
    - htop
    - tree
    - sysstat
    - python-pip
    - wget