---
- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: Install desired packages
  yum: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - htop
    - tree
    - sysstat
    - python-pip
    - wget